services:
  peace-app.api:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: PeaceApp.API/Dockerfile
    restart: always
  # sweet-manager_mysql:
  #   image: 'mysql:latest'
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: securepassword123
  #     MYSQL_PASSWORD: securepassword123
  #     MYSQL_DATABASE: sweetmanager
  #   restart: always
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
  #     timeout: 10s
  #     retries: 10
